services:
  web:
    build: .
    environment:
      MYENV: EXAMPLE
    volumes:
      - .:/code
  web_migrations:
    extends:
      service: web
    command: python /app/manage.py makemigrations
  web_migrate:
    extends:
      service: web
    command: python /app/manage.py migrate
  web_run:
    extends:
      service: web
    command: python /app/manage.py runserver 0.0.0.0:3000
    ports:
      - "3000:3000"